/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbamdc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CardBox service. Represents a row in the &quot;sbamdc_CardBox&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbamdc.model.impl.CardBoxModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbamdc.model.impl.CardBoxImpl}.
 * </p>
 *
 * @author Simon Bastian, Alexander Mueller, Diego Castellanos
 * @see CardBox
 * @see de.ki.sbamdc.model.impl.CardBoxImpl
 * @see de.ki.sbamdc.model.impl.CardBoxModelImpl
 * @generated
 */
@ProviderType
public interface CardBoxModel extends BaseModel<CardBox>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a card box model instance should use the {@link CardBox} interface instead.
	 */

	/**
	 * Returns the primary key of this card box.
	 *
	 * @return the primary key of this card box
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this card box.
	 *
	 * @param primaryKey the primary key of this card box
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this card box.
	 *
	 * @return the ID of this card box
	 */
	public long getId();

	/**
	 * Sets the ID of this card box.
	 *
	 * @param id the ID of this card box
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this card box.
	 *
	 * @return the group ID of this card box
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this card box.
	 *
	 * @param groupId the group ID of this card box
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this card box.
	 *
	 * @return the company ID of this card box
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this card box.
	 *
	 * @param companyId the company ID of this card box
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this card box.
	 *
	 * @return the user ID of this card box
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this card box.
	 *
	 * @param userId the user ID of this card box
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this card box.
	 *
	 * @return the user uuid of this card box
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this card box.
	 *
	 * @param userUuid the user uuid of this card box
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this card box.
	 *
	 * @return the user name of this card box
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this card box.
	 *
	 * @param userName the user name of this card box
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this card box.
	 *
	 * @return the create date of this card box
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this card box.
	 *
	 * @param createDate the create date of this card box
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this card box.
	 *
	 * @return the modified date of this card box
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this card box.
	 *
	 * @param modifiedDate the modified date of this card box
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this card box.
	 *
	 * @return the name of this card box
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this card box.
	 *
	 * @param name the name of this card box
	 */
	public void setName(String name);

	/**
	 * Returns the shared of this card box.
	 *
	 * @return the shared of this card box
	 */
	public boolean getShared();

	/**
	 * Returns <code>true</code> if this card box is shared.
	 *
	 * @return <code>true</code> if this card box is shared; <code>false</code> otherwise
	 */
	public boolean isShared();

	/**
	 * Sets whether this card box is shared.
	 *
	 * @param shared the shared of this card box
	 */
	public void setShared(boolean shared);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbamdc.model.CardBox cardBox);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbamdc.model.CardBox> toCacheModel();

	@Override
	public de.ki.sbamdc.model.CardBox toEscapedModel();

	@Override
	public de.ki.sbamdc.model.CardBox toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}