/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbamdc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Flashcard service. Represents a row in the &quot;sbamdc_Flashcard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbamdc.model.impl.FlashcardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbamdc.model.impl.FlashcardImpl}.
 * </p>
 *
 * @author Simon Bastian, Alexander Mueller, Diego Castellanos
 * @see Flashcard
 * @see de.ki.sbamdc.model.impl.FlashcardImpl
 * @see de.ki.sbamdc.model.impl.FlashcardModelImpl
 * @generated
 */
@ProviderType
public interface FlashcardModel extends BaseModel<Flashcard> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flashcard model instance should use the {@link Flashcard} interface instead.
	 */

	/**
	 * Returns the primary key of this flashcard.
	 *
	 * @return the primary key of this flashcard
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flashcard.
	 *
	 * @param primaryKey the primary key of this flashcard
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this flashcard.
	 *
	 * @return the ID of this flashcard
	 */
	public long getId();

	/**
	 * Sets the ID of this flashcard.
	 *
	 * @param id the ID of this flashcard
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this flashcard.
	 *
	 * @return the user ID of this flashcard
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this flashcard.
	 *
	 * @param userId the user ID of this flashcard
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this flashcard.
	 *
	 * @return the user uuid of this flashcard
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this flashcard.
	 *
	 * @param userUuid the user uuid of this flashcard
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the front side of this flashcard.
	 *
	 * @return the front side of this flashcard
	 */
	@AutoEscape
	public String getFrontSide();

	/**
	 * Sets the front side of this flashcard.
	 *
	 * @param frontSide the front side of this flashcard
	 */
	public void setFrontSide(String frontSide);

	/**
	 * Returns the back side of this flashcard.
	 *
	 * @return the back side of this flashcard
	 */
	@AutoEscape
	public String getBackSide();

	/**
	 * Sets the back side of this flashcard.
	 *
	 * @param backSide the back side of this flashcard
	 */
	public void setBackSide(String backSide);

	/**
	 * Returns the card box id_fk of this flashcard.
	 *
	 * @return the card box id_fk of this flashcard
	 */
	public long getCardBoxId_fk();

	/**
	 * Sets the card box id_fk of this flashcard.
	 *
	 * @param cardBoxId_fk the card box id_fk of this flashcard
	 */
	public void setCardBoxId_fk(long cardBoxId_fk);

	/**
	 * Returns the title of this flashcard.
	 *
	 * @return the title of this flashcard
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this flashcard.
	 *
	 * @param title the title of this flashcard
	 */
	public void setTitle(String title);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbamdc.model.Flashcard flashcard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbamdc.model.Flashcard> toCacheModel();

	@Override
	public de.ki.sbamdc.model.Flashcard toEscapedModel();

	@Override
	public de.ki.sbamdc.model.Flashcard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}