/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbamdc.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LearnProgress service. Represents a row in the &quot;sbamdc_LearnProgress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbamdc.model.impl.LearnProgressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbamdc.model.impl.LearnProgressImpl}.
 * </p>
 *
 * @author Simon Bastian, Alexander Mueller, Diego Castellanos
 * @see LearnProgress
 * @see de.ki.sbamdc.model.impl.LearnProgressImpl
 * @see de.ki.sbamdc.model.impl.LearnProgressModelImpl
 * @generated
 */
@ProviderType
public interface LearnProgressModel extends BaseModel<LearnProgress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learn progress model instance should use the {@link LearnProgress} interface instead.
	 */

	/**
	 * Returns the primary key of this learn progress.
	 *
	 * @return the primary key of this learn progress
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learn progress.
	 *
	 * @param primaryKey the primary key of this learn progress
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this learn progress.
	 *
	 * @return the ID of this learn progress
	 */
	public long getId();

	/**
	 * Sets the ID of this learn progress.
	 *
	 * @param id the ID of this learn progress
	 */
	public void setId(long id);

	/**
	 * Returns the user id_fk of this learn progress.
	 *
	 * @return the user id_fk of this learn progress
	 */
	public long getUserId_fk();

	/**
	 * Sets the user id_fk of this learn progress.
	 *
	 * @param userId_fk the user id_fk of this learn progress
	 */
	public void setUserId_fk(long userId_fk);

	/**
	 * Returns the card box id_fk of this learn progress.
	 *
	 * @return the card box id_fk of this learn progress
	 */
	public long getCardBoxId_fk();

	/**
	 * Sets the card box id_fk of this learn progress.
	 *
	 * @param cardBoxId_fk the card box id_fk of this learn progress
	 */
	public void setCardBoxId_fk(long cardBoxId_fk);

	/**
	 * Returns the flashcard id_fk of this learn progress.
	 *
	 * @return the flashcard id_fk of this learn progress
	 */
	public long getFlashcardId_fk();

	/**
	 * Sets the flashcard id_fk of this learn progress.
	 *
	 * @param flashcardId_fk the flashcard id_fk of this learn progress
	 */
	public void setFlashcardId_fk(long flashcardId_fk);

	/**
	 * Returns the progress of this learn progress.
	 *
	 * @return the progress of this learn progress
	 */
	public int getProgress();

	/**
	 * Sets the progress of this learn progress.
	 *
	 * @param progress the progress of this learn progress
	 */
	public void setProgress(int progress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbamdc.model.LearnProgress learnProgress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbamdc.model.LearnProgress> toCacheModel();

	@Override
	public de.ki.sbamdc.model.LearnProgress toEscapedModel();

	@Override
	public de.ki.sbamdc.model.LearnProgress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}